/* eslint-disable no-unused-vars */
export enum GameSocketTopic {
  //TOPICS EXTERNOS
  PLAYER_MESSAGE = 'PLAYER_MESSAGE',

  // TOPICS INTEROS
  NEW_ROUND_GAME = 'NEW_ROUND_GAME',
  UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS',
  UPDATE_PLAYER_STATUS = 'UPDATE_PLAYER_STATUS',
  PLAYER_ELIMINATED = 'PLAYER_ELIMINATED',
  CLOSE_GAME = 'CLOSE_GAME',
}
